name: metacompass
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mash>=2.0
  - skani
  - kmc
  - pilon
  - bbmap
  - bedtools>=2.30.0
  - bowtie2>=2.4.5
  - bzip2>=1.0.8
  - coreutils>=8.25
  - curl>=7.87.0
  - expat>=2.4.8
  - htslib>=1.16
  - megahit>=1.2.9
  - n50
  - ncbi-datasets-cli>=13.33.0
  - nextflow
  - openjdk>=11.0.15
  - pip>=22.2.2
  - pthread-stubs>=0.4
  - python>=3.10.8
  - pytest
  - pytest-cov
  - pysam
  - seaborn
  - biopython
  - minimap2
  - python_abi>=3.10
  - readline>=8.1.2
  - samtools>=1.16.1
  - setuptools>=63.4.2
  - seqkit>=2.3.1
  - wheel>=0.37.1
  - xz>=5.2.6
  - zlib>=1.2.13
  - zstd>=1.5.2
  - pip:
      - cycler
      - fonttools
      - kiwisolver
      - matplotlib
      - numpy
      - packaging
      - pandas
      - pillow
      - pyparsing
      - python-dateutil
      - pytz
      - six
