"""
DESCRIPTION
"""
#__author__ = "Victoria Cepeda

configfile: "config.json"

#include_prefix="https://"
#include_prefix + "rules"
#parse fasta/fastq files, run methaphyler and create fasta reference file #
include: 
    "reference_selection.py"
#map reads against reference genomes 
include:
    "mapping.py"

#build contigs using sam file
include:
    "build.py"

#ruleorder: rule1 > rule2 > rule3
rule all:
    input:expand('{prefix}/{sample}.assembly.out/mc.refseq.fna',sample=config["reads"]["S1"],prefix=config["prefix"]), 
    	  expand('{prefix}/{sample}.assembly.out/{sample}.sam',sample=config["reads"]["S1"],prefix=config["prefix"]),
          expand('{prefix}/{sample}.assembly.out/contigs.fasta',sample=config["reads"]["S1"],prefix=config["prefix"])
