CPPFLAGS = -g -Wall --std=c++11

all: get_FRC_data

clean: get_FRC_data
	rm $^ 

get_FRC_data: helpers.cpp single_read.cpp mate_pair.cpp contig.cpp flag_window.cpp flagged_region.cpp BED_parser.cpp FAI_parser.cpp feature_calculator.cpp get_FRC_data.cpp
